name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest
    environment: ci
    services:
      postgres:
        image: postgres:18.4-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}
      EXTERNAL_API_URL: https://mockapi-furw4tenlq-ez.a.run.app/data
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: pnpm/action-setup@v6.0.9

      - uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm --filter server exec prisma migrate deploy

      - run: pnpm --filter server run typecheck

      - run: pnpm eslint server

      - run: pnpm --filter server run test

  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: pnpm/action-setup@v6.0.9

      - uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm --filter client run typecheck

      - run: pnpm eslint client

      - run: pnpm --filter client run test

      - run: pnpm --filter client run build

  deploy:
    needs: [server, client]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: prod
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v7.0.0

      - uses: pnpm/action-setup@v6.0.9

      - uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm --filter server exec prisma migrate deploy

      - uses: sws2apps/render-deployment@v2.1.0
        with:
          serviceId: ${{ secrets.RENDER_SERVER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}

      - uses: sws2apps/render-deployment@v2.1.0
        with:
          serviceId: ${{ secrets.RENDER_CLIENT_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
